### ISSUE TITLE
Changing the position of searching color

### ISSUE THREAD

**Issue by Rahul-2006** [Rahul-2006/Color-Picker#1]
When trying to search a color the picked color is covered by the color search
So try to changing the position of color search to make the searched color visible

**Comment by LucioPalmucci** [comment]
Hey i dont understand whats going on with the issue. For me the page works fine, the only problem that i found is that when you pick black, the "Selected Color:" text is not visible.

**Comment by Rahul-2006** [comment]
![Screenshot 2024-09-12 112017](https://github.com/user-attachments/assets/ad059790-86f1-4646-8744-7156e2f01e49)
This is the problem. The box which shows the color while selecting covers the selected color
Kindly fix it
